spring.application.name=shoppingmall

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/shoppingmall}
spring.datasource.username=${DB_USERNAME:${user.name}}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=${DB_DRIVER_CLASS_NAME:org.postgresql.Driver}

spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

app.admin.email=${ADMIN_EMAIL:admin@shoppingmall.com}
app.admin.password=${ADMIN_PASSWORD:Admin1234!}
app.admin.name=${ADMIN_NAME:기본 관리자}
